### ISSUE TITLE
Do not remove unused functions annotated with [@zero_alloc]

### ISSUE THREAD

**Issue by gretay-js** [ocaml-flambda/flambda-backend#1273]
Do not eliminate functions annotated with `[@zero_alloc]` attributes introduce in https://github.com/ocaml-flambda/flambda-backend/pull/1157, because these annotations are checked in the backend, see example in https://github.com/ocaml-flambda/flambda-backend/pull/1157#issuecomment-1488202057.

**Comment by mshinwell** [comment]
It's not entirely clear to me this is the right thing.  Can we arrange matters so that an "unused attribute" warning is produced if the relevant function doesn't get checked?

**Comment by lthls** [comment]
> It's not entirely clear to me this is the right thing. Can we arrange matters so that an "unused attribute" warning is produced if the relevant function doesn't get checked?

That's harder, because Flambda 2 routinely copies functions bodies and discards the old ones. We don't have a good way to signal that we're removing the last copy of a function given as input.

I guess we could register all these attributes early in the compiler and match them with actual functions during the allocation check, but it seems a bit complex.

**Comment by gretay-js** [comment]
> I guess we could register all these attributes early in the compiler and match them with actual functions during the allocation check, but it seems a bit complex.
I can do it, and it is better than nothing in terms of soundness, but it's not clear what a user would do to fix the problem (add another spurious use of the function? surely the compiler can manage it on its own).

This seems to be a problem for both flambda and flambda2.

**Comment by mshinwell** [comment]
I suggest we do the rollout of the feature, and see in practice if anyone flags this up.

**Comment by gretay-js** [comment]
duplicate of #1341
