### ISSUE TITLE
How to test new amd64 instructions?

### ISSUE THREAD

**Issue by Kakadu** [ocaml-flambda/flambda-backend#1794]
There are some examples in tests/simd, I tried them, but only think I got is a call of C primitive. So I decided to call compiler out of the source tree of flambda2. As you can see, it tried to call C stubs, which is not what I expect. 

How to invoke compiler properly? I'm on amd64

```ocaml
➜  flambda_backend_test make                                             
/media/work/asp/flambda-backend/_install/bin/ocamlopt.opt -I /media/work/asp/flambda-backend/_install/lib/ocaml -extension simd -S test1.ml -o test1.exe
/usr/bin/ld: test1.o: in function `camlTest1__entry':
:(.text+0x1d): undefined reference to `caml_nativeint_popcnt_unboxed_to_untagged'
/usr/bin/ld: test1.o: in function `camlTest1':
:(.data+0x50): undefined reference to `caml_nativeint_popcnt_unboxed_to_untagged'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
make: *** [Makefile:7: test1.exe] Error 2
➜  flambda_backend_test cat test1.ml                                                                                                                                         flambda-backend
open Stdlib

external popcnt : nativeint -> nativeint = "" "caml_nativeint_popcnt_unboxed_to_untagged" [@@noalloc] [@@unboxed]

let() = Printf.printf "%d\n" (popcnt 15n |> Nativeint.to_int)
```

**Comment by xclerc** [comment]
For `popcnt`, I think you should use [this definition](https://github.com/janestreet/ocaml_intrinsics/blob/master/src/nativeint.ml#L38):
```
external count_set_bits
  :  (nativeint[@unboxed])
  -> (int[@untagged])
  = "caml_nativeint_popcnt" "caml_nativeint_popcnt_unboxed_to_untagged"
  [@@noalloc] [@@builtin] [@@no_effects] [@@no_coeffects]
```
And it is possibly easier to use the whole package
available at https://github.com/janestreet/ocaml_intrinsics.

**Comment by Kakadu** [comment]
Nothing changes... Maybe I have compiled it wrong? Should `autoconf && ./configure --prefix=$(opam var root)/flambda-backend --enable-middle-end=flambda2 && make _install` be enough?

```
➜  flambda_backend_test make
/media/work/asp/flambda-backend/_install/bin/ocamlopt.opt -I /media/work/asp/flambda-backend/_install/lib/ocaml -extension simd -S test1.ml -o test1.exe
/usr/bin/ld: test1.o: in function `camlTest1':
:(.data+0x50): undefined reference to `caml_nativeint_popcnt_unboxed_to_untagged'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
make: *** [Makefile:7: test1.exe] Error 2
➜  flambda_backend_test cat test1.ml
open Stdlib

external count_set_bits
  :  (nativeint[@unboxed])
  -> (int[@untagged])
  = "caml_nativeint_popcnt" "caml_nativeint_popcnt_unboxed_to_untagged"
  [@@noalloc] [@@builtin] [@@no_effects] [@@no_coeffects]

let () = Printf.printf "%d\n" (count_set_bits 15n)
➜  flambda_backend_test /media/work/asp/flambda-backend/_install/bin/ocamlopt.opt -version     
4.14.1+jst
```

**Comment by xclerc** [comment]
I used the same command to build the compiler
(well, except the prefix and the underscore in
front of `install`). Are you positive you CPU
supports `popcntq`? If it does, maybe we have
something wrong in the detection.

**Comment by xclerc** [comment]
Actually, I don't think there is any kind of
detection in the compiler base, the detection
happens in `ocaml_intrinsics`.

**Comment by Kakadu** [comment]
> Are you positive your CPU supports `popcntq`?

Yes

> ➜  flambda_backend_test cat /proc/cpuinfo|grep popcnt | head -n1                                                                                                              
> flags                : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe **popcnt** tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d

**Comment by Kakadu** [comment]
To test the ocaml_intrinsics library I tried to install this compiler as an opam switch, but got into issues.
I followed `Testing the compiler built locally with OPAM` and got stuck on the step with `opam custom-install`

```
➜  flambda-backend git:(main) opam custom-install ocaml-variants.4.14.1+flambda2 -- make install_for_opam
[ERROR] Package conflict!
  * No agreement on the version of ocaml-variants:
    - ocaml-variants = 4.14.1+flambda2
    - (invariant) → ocaml-variants = 4.14.1+options
    You can temporarily relax the switch invariant with `--update-invariant'
```
Is there a simple explanation?

**Comment by Kakadu** [comment]
It looks like opam is still not working properly. 
But I understood what was wrong with my previous attempt. I needed to add fake stub for external function. This stub is not called but still required because of machinery about  intricsic's declarations
