### ISSUE TITLE
Port #10461, #10498: `caml_send*` helper functions

### ISSUE THREAD

**Issue by gretay-js** [ocaml-flambda/flambda-backend#206]
https://github.com/ocaml/ocaml/pull/10461
https://github.com/ocaml/ocaml/pull/10498

Port them **after** Safepoints.

**Comment by gretay-js** [comment]
This PR goes with #213, @mshinwell said he would port them.

**Comment by mshinwell** [comment]
This is all that needs porting.  It can be done before safepoints, I will make a PR:
ocaml/ocaml@e608b7c95af93db18d18104c9347e19ff50b252e

**Comment by mshinwell** [comment]
This has been done as part of the safepoints work
