### ISSUE TITLE
Recursive modules sometimes infer layout `any` for a type incorrectly

### ISSUE THREAD

**Issue by ncik-roberts** [ocaml-flambda/flambda-backend#3081]
See test demonstrating bad behavior, where the order of `include S_value with type t := t` and `include S_any with type t := t` affects what programs are legal:

https://github.com/ocaml-flambda/flambda-backend/blob/0571648a475816b6f025a4cf4aea2a546f188330/ocaml/testsuite/tests/typing-layouts/recursive_modules.ml#L1-L62

**Comment by goldfirere** [comment]
How did this arise? Is fixing this high priority? And is there a particular reason this is on GitHub instead of our usual internal system?

(For what it's worth, I'm not surprised about this.)

**Comment by ncik-roberts** [comment]
It's low priority. I also (now) tracked it in our internal system.

**Comment by goldfirere** [comment]
OK. I will close this then to avoid the dup.
