### ISSUE TITLE
Non-terminating module initialisers cause linker errors

### ISSUE THREAD

**Issue by mshinwell** [ocaml-flambda/flambda-backend#413]
It looks like the let-symbol bindings for module blocks are being dropped if the module initialiser is non-terminating.  It's not entirely clear to me how to fix this without compile-time performance overhead.  There seems to be a relevant comment in `closure_conversion.ml` on line 1351.  The following should reproduce the linker error:
```
x.ml:  let x = while true do () done
x.mli: val x : unit
y.ml:  let a = X.x, X.x
```

**Comment by Gbury** [comment]
This should have been solved by #458
